article: https://www.hackster.io/158970/hardwario-iot-kit-color-game-e70dfb
articles:
  - title: HARWDARIO IoT Kit Color Game
    url: https://www.hackster.io/158970/hardwario-iot-kit-color-game-e70dfb
    description: Teach your kids colors in different languages with HARDWARIO IoT Kit, LED lights and this simple color game.
    video: https://hackster.imgix.net/uploads/attachments/894026/color_game_1q52JSQ4zK.gif?auto=compress&gifq=35&w=900&h=675&fit=min&fm=mp4
assembly:
  - name: HARDWARIO Button Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Power Module
